UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=1;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=2;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=3;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=4;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=5;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=6;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=7;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=8;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=9;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=10;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=11;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=12;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=13;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=14;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=15;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=16;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=17;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=18;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=19;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=20;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=21;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=22;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=23;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=24;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=25;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=26;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=27;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=28;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=29;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=30;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=31;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=32;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=33;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=34;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=35;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=36;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=37;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=38;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=39;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=40;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=41;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=42;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=43;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=44;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=45;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=46;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=47;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=48;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=49;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=50;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=51;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=52;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=53;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=54;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=55;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=56;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=57;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=58;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=59;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=60;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=61;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=62;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=63;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=64;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=65;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=66;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=67;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=68;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=69;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=70;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=71;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=72;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=73;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=74;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=75;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=76;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=77;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=78;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=79;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=80;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=81;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=82;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=83;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=84;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=85;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=86;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=87;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=88;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=89;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=90;
UPDATE delivery_status SET Status='anulowane' WHERE Status_ID=91;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=92;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=93;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=94;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=95;
UPDATE delivery_status SET Status='w drodze' WHERE Status_ID=96;
UPDATE delivery_status SET Status='dostarczone' WHERE Status_ID=97;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=98;
UPDATE delivery_status SET Status='w magazynie' WHERE Status_ID=99;
UPDATE delivery_status SET Status='oczekuje' WHERE Status_ID=100;