insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (1, 0, 1, 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (2, 0, 2, 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (3, 0, 3, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (4, 0, 4, 'id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (5, 0, 5, 'mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (6, 0, 6, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (7, 0, 7, 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (8, 0, 8, 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (9, 0, 9, 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (10, 0, 10, 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (11, 0, 11, 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (12, 0, 12, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (13, 0, 13, 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (14, 0, 14, 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (15, 0, 15, 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (16, 0, 16, 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (17, 0, 17, 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (18, 0, 18, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (19, 0, 19, 'nunc proin at turpis a pede posuere nonummy integer non');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (20, 0, 20, 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (21, 0, 21, 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (22, 0, 22, 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (23, 0, 23, 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (24, 0, 24, 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (25, 0, 25, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (26, 0, 26, 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (27, 0, 27, 'enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (28, 0, 28, 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (29, 0, 29, 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (30, 0, 30, 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (31, 0, 31, 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (32, 0, 32, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (33, 0, 33, 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (34, 0, 34, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (35, 0, 35, 'purus phasellus in felis donec semper sapien a libero nam');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (36, 0, 36, 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (37, 0, 37, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (38, 0, 38, 'dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (39, 0, 39, 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (40, 0, 40, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (41, 0, 41, 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (42, 0, 42, 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (43, 0, 43, 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (44, 0, 44, 'cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (45, 0, 45, 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (46, 0, 46, 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (47, 0, 47, 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (48, 0, 48, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (49, 0, 49, 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (50, 0, 50, 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (51, 0, 51, 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (52, 0, 52, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (53, 0, 53, 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (54, 0, 54, 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (55, 0, 55, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (56, 0, 56, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (57, 0, 57, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (58, 0, 58, 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (59, 0, 59, 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (60, 0, 60, 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (61, 0, 61, 'massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (62, 0, 62, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (63, 0, 63, 'magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (64, 0, 64, 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (65, 0, 65, 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (66, 0, 66, 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (67, 0, 67, 'augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (68, 0, 68, 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (69, 0, 69, 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (70, 0, 70, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (71, 0, 71, 'sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (72, 0, 72, 'nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (73, 0, 73, 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (74, 0, 74, 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (75, 0, 75, 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (76, 0, 76, 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (77, 0, 77, 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (78, 0, 78, 'porttitor pede justo eu massa donec dapibus duis at velit');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (79, 0, 79, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (80, 0, 80, 'felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (81, 0, 81, 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (82, 0, 82, 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (83, 0, 83, 'praesent id massa id nisl venenatis lacinia aenean sit amet');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (84, 0, 84, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (85, 0, 85, 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (86, 0, 86, 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (87, 0, 87, 'aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (88, 0, 88, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (89, 0, 89, 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (90, 0, 90, 'donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (91, 0, 91, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (92, 0, 92, 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (93, 0, 93, 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (94, 0, 94, 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (95, 0, 95, 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (96, 0, 96, 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (97, 0, 97, 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (98, 0, 98, 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (99, 0, 99, 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in');
insert into delivery_status (Status_ID, Status, Order_ID, Uwagi) values (100, 0, 100, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
