insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (1, 'integer a nibh in quis justo maecenas rhoncus aliquam lacus', '2019-07-21 22:33:00', 'Hongsipu', 'Holyland');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (2, 'sed magna at nunc commodo placerat praesent blandit nam', '2005-09-02 18:10:32', 'Tuopu Luke', 'Terram');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (3, 'quam turpis adipiscing lorem vitae', '2007-08-23 22:54:57', 'Dāngām', 'Dodell');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (4, 'nisi eu orci mauris', '2019-09-12 19:40:56', 'Dengfang', 'Went');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (5, 'odio in hac habitasse platea dictumst maecenas ut massa quis', '2003-02-22 10:45:30', 'Áno Liósia', 'Eschalette');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (6, 'blandit mi in porttitor', '2009-09-30 13:55:55', 'Saint-Quentin', 'Smidmore');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (7, 'sollicitudin mi', '2013-09-15 12:43:12', 'Guider', 'Worlidge');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (8, 'nunc commodo placerat praesent blandit', '2004-01-07 08:39:53', 'Jieshui', 'Roullier');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (9, 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem', '2006-05-20 07:46:53', 'Courtaboeuf', 'Roft');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (10, 'tortor duis mattis egestas metus', '2002-02-21 20:44:08', 'Grodków', 'Yearnes');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (11, 'eget massa tempor convallis nulla', '2016-01-04 23:36:26', 'Bader', 'Gabel');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (12, 'eleifend donec ut', '2017-02-26 13:53:40', 'Haninge', 'Lube');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (13, 'bibendum felis sed interdum venenatis turpis enim blandit mi in', '2014-06-02 22:18:39', 'Mahates', 'Hoonahan');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (14, 'sed interdum venenatis turpis enim blandit mi in porttitor pede', '2011-11-18 01:40:02', 'Rouyuan', 'Camock');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (15, 'volutpat', '2003-06-01 16:10:38', 'Turmus‘ayyā', 'Searchfield');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (16, 'ultrices phasellus id sapien in sapien iaculis congue vivamus', '2000-05-06 17:05:47', 'Chavães', 'Neary');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (17, 'sollicitudin mi sit amet lobortis', '2004-04-21 21:57:17', 'Unión', 'Rankling');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (18, 'sapien non mi integer ac neque duis', '2008-03-18 20:40:02', 'Ambato', 'Pinckstone');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (19, 'interdum in ante', '2000-06-04 20:09:29', 'Chernukha', 'Pearmain');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (20, 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque', '2004-08-26 04:10:32', 'Iradan', 'Bohl');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (21, 'maecenas pulvinar lobortis est phasellus sit amet erat', '2021-07-03 20:22:50', 'Chorkówka', 'Comrie');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (22, 'dictumst morbi vestibulum velit id pretium iaculis diam', '2000-05-13 17:43:44', 'Huangtukuang', 'Marham');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (23, 'non mattis pulvinar nulla pede ullamcorper augue a suscipit', '2005-07-10 05:57:54', 'Maliq', 'Gye');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (24, 'vel accumsan tellus nisi eu orci mauris lacinia sapien', '2015-06-06 02:41:23', 'Tambalisa', 'Caruth');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (25, 'orci', '2004-09-11 09:54:33', 'Vila Nova Sintra', 'Attridge');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (26, 'nec sem duis', '2014-09-20 18:55:05', 'Hobo', 'Fearn');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (27, 'pede malesuada in imperdiet et commodo vulputate justo in blandit', '2019-05-12 00:20:25', 'Ban Nong Wua So', 'Gath');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (28, 'morbi vel lectus in quam fringilla rhoncus', '2018-04-29 12:36:24', 'Goundam', 'Jakucewicz');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (29, 'justo lacinia eget tincidunt eget', '2005-05-26 04:46:17', 'Vale de São Cosme', 'Pauncefoot');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (30, 'duis mattis', '2010-05-08 04:45:17', 'Sortavala', 'Youthead');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (31, 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus', '2000-03-11 01:53:29', 'Irving', 'Balma');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (32, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur', '2003-10-30 21:58:35', 'Tobias Fornier', 'Mowday');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (33, 'convallis tortor', '2002-06-15 10:08:57', 'Ljungbyholm', 'Gossop');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (34, 'vulputate ut ultrices vel augue vestibulum ante ipsum primis', '2000-09-12 06:04:00', 'Kalamáta', 'Adanet');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (35, 'tellus nisi eu orci mauris lacinia sapien quis', '2009-07-27 18:08:30', 'Atescatempa', 'Asman');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (36, 'vel accumsan tellus nisi eu orci mauris', '2010-10-12 05:04:08', 'Hengjie', 'Lantiffe');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (37, 'in', '2004-03-04 09:45:26', 'Koper', 'Dwerryhouse');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (38, 'ut at dolor quis odio consequat', '2009-10-11 09:21:03', 'Banjar Cemenggon', 'Papachristophorou');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (39, 'erat fermentum', '2011-06-04 05:24:57', 'Talugtug', 'Hugill');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (40, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi', '2021-03-17 01:53:22', 'Pamotan', 'Seakes');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (41, 'ac neque duis bibendum morbi', '2001-12-25 03:14:01', 'Huwei', 'Cargenven');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (42, 'ligula in lacus curabitur at ipsum ac', '2008-09-21 06:47:34', 'Bukavu', 'McGaugan');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (43, 'vehicula consequat morbi a', '2014-05-15 13:38:36', 'Yarumal', 'Curbishley');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (44, 'vel ipsum praesent blandit lacinia erat vestibulum sed', '2017-02-22 09:10:36', 'Tucson', 'Altimas');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (45, 'luctus et ultrices posuere cubilia', '2003-04-24 07:50:20', 'Tebingtinggi', 'Summerill');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (46, 'sed tristique in tempus', '2019-08-20 11:16:32', 'Wang Sam Mo', 'Ayshford');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (47, 'consectetuer adipiscing elit', '2020-06-28 09:57:55', 'Nikolayevka', 'Glass');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (48, 'cursus id turpis integer aliquet massa id lobortis convallis tortor', '2021-08-01 00:47:36', 'Balogo', 'Hathwood');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (49, 'blandit non interdum in ante vestibulum ante ipsum primis', '2008-01-14 07:43:36', 'Purificación', 'Grayer');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (50, 'consectetuer eget rutrum at lorem integer tincidunt', '2017-01-27 20:49:18', 'Owczarnia', 'Bener');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (51, 'id ligula suspendisse ornare consequat lectus in est risus', '2018-12-12 13:41:35', 'La Cruz', 'Klaaassen');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (52, 'volutpat dui maecenas tristique est et', '2012-12-18 13:03:51', 'Limoeiro', 'Idney');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (53, 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', '2010-09-16 08:03:41', 'Lianga', 'Gensavage');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (54, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor', '2015-05-07 19:57:16', 'Laholm', 'McComas');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (55, 'neque duis bibendum morbi non quam', '2000-11-10 07:22:37', 'Xamba', 'Simonazzi');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (56, 'est lacinia nisi venenatis tristique', '2001-03-01 00:49:22', 'Suishan', 'Neaverson');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (57, 'vulputate', '2021-05-04 12:26:03', 'Campanário', 'Sawday');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (58, 'donec quis orci eget orci', '2007-01-07 14:04:00', 'Xinzhou', 'Chown');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (59, 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci', '2011-05-17 10:03:36', 'Armenia', 'Barcroft');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (60, 'curabitur at ipsum ac tellus semper interdum', '2020-10-24 11:33:21', 'Zhoujiadian', 'Leitch');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (61, 'et eros vestibulum ac est lacinia nisi', '2010-12-23 12:04:36', 'Jianlong', 'Greenhalgh');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (62, 'et ultrices posuere cubilia curae donec pharetra magna vestibulum', '2018-08-16 01:29:16', 'Phatthalung', 'MacIlurick');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (63, 'aliquam augue quam sollicitudin vitae consectetuer', '2011-04-30 05:06:10', 'Anfeng', 'Attenborrow');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (64, 'quam fringilla', '2003-01-19 19:29:51', 'Wojnicz', 'Oppy');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (65, 'luctus', '2005-06-05 09:25:57', 'Panaoti', 'Sergent');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (66, 'dis parturient', '2007-12-05 07:51:55', 'Cojutepeque', 'Rudwell');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (67, 'faucibus orci luctus et ultrices posuere cubilia', '2004-10-15 01:05:56', 'Turrialba', 'Teggart');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (68, 'rutrum rutrum neque aenean auctor gravida', '2020-10-23 19:43:19', 'Cojutepeque', 'MacGarvey');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (69, 'justo sollicitudin ut suscipit a', '2007-02-03 05:19:32', 'Zhijiang', 'Southgate');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (70, 'suspendisse potenti nullam', '2012-05-23 20:00:36', 'Tadmur', 'Hamerton');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (71, 'mauris vulputate elementum nullam varius nulla facilisi', '2020-08-31 08:35:23', 'Wanmao', 'Weatherhead');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (72, 'nisl duis ac nibh', '2021-12-03 00:23:38', 'Huolongmen', 'Easterfield');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (73, 'in hac habitasse platea dictumst aliquam augue quam', '2003-11-25 15:57:43', 'Liushi', 'Blesdill');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (74, 'eleifend pede libero quis orci nullam molestie nibh in lectus', '2022-01-02 17:49:57', 'Mekarjaya Satu', 'Jaime');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (75, 'vitae quam suspendisse', '2011-10-24 02:56:06', 'Nanfeng', 'Skittrell');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (76, 'etiam vel augue vestibulum rutrum rutrum', '2005-03-24 20:53:35', 'Causip', 'Rippingall');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (77, 'est risus auctor sed tristique', '2018-10-25 00:12:16', 'Borok', 'Eldritt');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (78, 'consectetuer eget rutrum at lorem integer', '2007-02-01 15:53:44', 'Nobinobi', 'McCourtie');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (79, 'dolor vel est', '2006-08-31 00:35:05', 'Yiqi', 'Alkin');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (80, 'velit vivamus vel', '2011-12-25 08:14:44', 'Gaoguan', 'Ganny');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (81, 'lorem integer tincidunt', '2015-02-23 10:57:22', 'Estreito', 'Branscombe');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (82, 'vestibulum ac est lacinia nisi', '2021-09-28 03:29:17', 'São Pedro de Trafaria', 'Feben');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (83, 'in tempus sit amet sem fusce consequat', '2009-07-19 07:46:17', 'Ponta Delgada', 'Dufer');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (84, 'urna pretium nisl ut volutpat sapien arcu', '2003-10-09 15:18:58', 'Chociwel', 'Lowey');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (85, 'feugiat non pretium quis lectus suspendisse potenti in eleifend', '2008-10-14 21:31:32', 'Heishui', 'Delacourt');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (86, 'tempor convallis nulla neque libero convallis eget eleifend luctus', '2001-06-16 23:23:39', 'Kertorejo', 'Geddis');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (87, 'massa', '2011-05-04 08:32:18', '‘Amrān', 'Hamflett');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (88, 'viverra eget congue', '2007-04-28 17:07:15', 'Yuezhao', 'Iacapucci');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (89, 'vestibulum proin eu mi nulla ac enim', '2004-06-21 20:16:43', 'Ljungsbro', 'Welberry');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (90, 'dolor quis odio consequat varius integer ac', '2009-02-15 21:53:20', 'Yangyu', 'Conant');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (91, 'non', '2014-04-29 07:21:27', 'Xuguang', 'Wakeford');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (92, 'iaculis congue', '2004-02-02 18:37:37', 'Shuanglu', 'Boutellier');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (93, 'ipsum integer a nibh in quis justo maecenas rhoncus', '2013-10-10 00:49:47', 'Šilheřovice', 'Glencross');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (94, 'aenean lectus', '2009-10-24 23:53:32', 'Lingyuan', 'Fidell');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (95, 'nisi venenatis tristique fusce', '2004-12-05 01:46:05', 'Daqiao', 'Sieur');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (96, 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', '2011-10-03 01:36:28', 'Funan Chengguanzhen', 'Beardwell');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (97, 'eleifend luctus ultricies eu', '2014-11-28 10:30:18', 'San Antonio', 'Cleverley');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (98, 'nec euismod', '2009-10-13 11:55:18', 'Lubāna', 'Peyntue');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (99, 'sit amet turpis elementum ligula', '2014-02-16 07:47:22', 'Bulbul', 'Fishpool');
insert into trainings (Training_ID, Temat, Data, Miejsce, Nazwisko_prowadzacego) values (100, 'velit eu est congue elementum in hac habitasse platea dictumst', '2004-10-31 16:34:02', 'Güiria', 'Skitral');
