insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (1, 'Audi', 'S6', 16, 359955);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (2, 'Mercedes-Benz', 'SL-Class', 26, 385546);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (3, 'Jeep', 'Patriot', 20, 850908);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (4, 'Chevrolet', 'Impala', 11, 487809);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (5, 'Mercedes-Benz', '300SL', 18, 577095);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (6, 'Audi', 'Quattro', 18, 202298);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (7, 'Ford', 'F150', 26, 295931);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (8, 'Mercedes-Benz', 'M-Class', 21, 920463);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (9, 'Chevrolet', 'Astro', 28, 980266);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (10, 'Daihatsu', 'Rocky', 16, 901236);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (11, 'Merkur', 'XR4Ti', 14, 557620);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (12, 'Mercedes-Benz', 'C-Class', 11, 600314);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (13, 'Mercedes-Benz', 'E-Class', 19, 924199);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (14, 'Chevrolet', 'Avalanche 1500', 29, 46363);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (15, 'Saab', '900', 24, 969729);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (16, 'Mitsubishi', 'Eclipse', 12, 304738);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (17, 'Toyota', 'Venza', 26, 419119);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (18, 'Toyota', '4Runner', 25, 625493);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (19, 'Mitsubishi', 'Galant', 25, 281985);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (20, 'Saturn', 'Sky', 19, 644996);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (21, 'Dodge', 'Dakota Club', 25, 577518);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (22, 'Ford', 'F450', 12, 484685);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (23, 'Suzuki', 'Swift', 11, 906848);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (24, 'Mercedes-Benz', '400SEL', 20, 82911);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (25, 'Maybach', '62', 15, 106937);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (26, 'Mercedes-Benz', 'E-Class', 13, 743491);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (27, 'Eagle', 'Vision', 25, 506811);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (28, 'Mitsubishi', 'Montero', 19, 525309);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (29, 'Volkswagen', 'Scirocco', 20, 695518);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (30, 'GMC', 'Yukon XL 1500', 27, 543675);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (31, 'GMC', 'Yukon XL 1500', 17, 515318);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (32, 'Buick', 'Reatta', 27, 877734);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (33, 'Mercedes-Benz', 'SL-Class', 28, 255574);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (34, 'Volvo', 'C30', 18, 50399);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (35, 'Ford', 'Bronco II', 25, 480970);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (36, 'Chevrolet', 'Astro', 24, 498611);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (37, 'Ford', 'Probe', 21, 741495);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (38, 'Hummer', 'H3', 25, 121394);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (39, 'Porsche', '944', 21, 756668);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (40, 'Ford', 'Five Hundred', 19, 674514);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (41, 'Chevrolet', 'Silverado 2500', 15, 288195);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (42, 'Nissan', 'Quest', 28, 583967);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (43, 'Mercury', 'Grand Marquis', 18, 633902);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (44, 'Chevrolet', 'Silverado 2500', 20, 878672);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (45, 'Porsche', '968', 12, 703150);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (46, 'Mazda', 'Mazdaspeed6', 12, 482695);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (47, 'Isuzu', 'Hombre', 18, 832247);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (48, 'Jeep', 'Compass', 30, 546792);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (49, 'Chrysler', 'PT Cruiser', 19, 759720);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (50, 'Volvo', 'C70', 21, 257334);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (51, 'Pontiac', 'Grand Prix', 16, 684035);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (52, 'Subaru', 'Impreza', 11, 142235);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (53, 'Chevrolet', 'Tracker', 10, 55515);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (54, 'Geo', 'Tracker', 10, 555652);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (55, 'Mercury', 'Villager', 25, 108859);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (56, 'Infiniti', 'Q', 17, 53417);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (57, 'Saab', '9-5', 24, 51754);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (58, 'Nissan', 'Pathfinder', 27, 957183);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (59, 'Mercedes-Benz', 'S-Class', 23, 13771);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (60, 'Nissan', 'Frontier', 29, 561638);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (61, 'Ford', 'GT500', 13, 296071);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (62, 'Honda', 'Accord', 25, 923272);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (63, 'Hummer', 'H2 SUV', 16, 891135);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (64, 'Chrysler', 'Town & Country', 17, 73657);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (65, 'Honda', 'CR-V', 17, 643680);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (66, 'Nissan', 'Sentra', 27, 682319);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (67, 'Chrysler', 'Sebring', 18, 37115);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (68, 'Toyota', 'Highlander Hybrid', 11, 972298);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (69, 'GMC', 'Acadia', 30, 850553);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (70, 'Mercedes-Benz', 'SLK-Class', 14, 716342);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (71, 'Rolls-Royce', 'Phantom', 17, 278460);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (72, 'Chevrolet', 'Suburban 2500', 27, 823917);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (73, 'Oldsmobile', 'Cutlass', 19, 44742);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (74, 'Jeep', 'Grand Cherokee', 17, 487034);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (75, 'Mazda', 'Navajo', 13, 105028);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (76, 'Volkswagen', 'Touareg', 20, 468133);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (77, 'Honda', 'Prelude', 13, 281650);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (78, 'Lincoln', 'Navigator', 26, 778984);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (79, 'BMW', 'M Roadster', 18, 279629);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (80, 'Volvo', 'XC70', 18, 673441);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (81, 'Mercedes-Benz', 'M-Class', 16, 268165);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (82, 'Audi', 'Q7', 28, 67909);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (83, 'Land Rover', 'Range Rover', 28, 916331);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (84, 'Dodge', 'Daytona', 22, 526152);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (85, 'Honda', 'del Sol', 26, 79738);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (86, 'Bentley', 'Continental', 12, 39741);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (87, 'GMC', '3500', 12, 909205);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (88, 'Toyota', 'Corolla', 26, 710605);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (89, 'Daewoo', 'Lanos', 12, 627392);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (90, 'Chevrolet', 'Tahoe', 20, 88247);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (91, 'Toyota', 'Camry', 27, 668629);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (92, 'Audi', 'A5', 25, 994922);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (93, 'Mercedes-Benz', 'S-Class', 17, 589696);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (94, 'Land Rover', 'Discovery', 16, 97189);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (95, 'Ford', 'F250', 12, 650932);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (96, 'Ford', 'Mustang', 26, 773973);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (97, 'Audi', 'S4', 14, 377991);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (98, 'Jaguar', 'XJ Series', 23, 272014);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (99, 'Hyundai', 'Accent', 23, 55709);
insert into trucks (Truck_ID, Marka, Model, Spalanie, Przebieg) values (100, 'Chevrolet', 'HHR', 17, 476598);
