UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=1;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=2;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=3;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=4;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=5;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=6;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=7;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=8;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=9;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=10;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=11;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=12;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=13;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=14;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=15;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=16;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=17;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=18;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=19;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=20;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=21;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=22;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=23;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=24;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=25;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=26;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=27;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=28;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=29;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=30;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=31;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=32;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=33;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=34;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=35;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=36;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=37;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=38;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=39;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=40;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=41;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=42;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=43;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=44;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=45;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=46;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=47;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=48;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=49;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=50;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=51;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=52;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=53;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=54;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=55;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=56;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=57;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=58;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=59;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=60;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=61;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=62;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=63;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=64;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=65;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=66;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=67;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=68;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=69;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=70;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=71;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=72;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=73;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=74;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=75;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=76;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=77;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=78;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=79;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=80;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=81;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=82;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=83;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=84;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=85;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=86;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=87;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=88;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=89;
UPDATE trucksinservice SET Progress='oczekujący' WHERE Truck_serviced_ID=90;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=91;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=92;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=93;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=94;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=95;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=96;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=97;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=98;
UPDATE trucksinservice SET Progress='w trakcie' WHERE Truck_serviced_ID=99;
UPDATE trucksinservice SET Progress='wydany' WHERE Truck_serviced_ID=100;